version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "github/codeql-action/init"
      - dependency-name: "github/codeql-action/analyze"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
