default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8 # v4.4.0
    hooks:
      - id: conventional-pre-commit
