from __future__ import annotations

from contextlib import contextmanager, redirect_stderr, redirect_stdout
from importlib.util import module_from_spec, spec_from_file_location
from io import StringIO
from pathlib import Path
from tempfile import TemporaryDirectory
from textwrap import dedent
from unittest import TestCase, mock

SCRIPT_PATH = Path(__file__).resolve().parents[1] / "sync_guide_labels.py"
SPEC = spec_from_file_location("sync_guide_labels", SCRIPT_PATH)
MODULE = module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dedent(content).lstrip(), encoding="utf-8")


def build_guide_tree(root: Path) -> None:
    write(root / "guides/injection/README.md", "# Injection\n")
    write(root / "guides/injection/xss/README.md", "# Cross-site scripting (XSS)\n")
    write(root / "guides/request-authenticity/README.md", "# Request Authenticity\n")
    write(root / "guides/sensitive-data-exposure/README.md", "# Sensitive Data Exposure\n")
    write(root / "guides/cross-origin-communication/README.md", "# Cross-origin Communication\n")


@contextmanager
def patched_repo(root: Path):
    with (
        mock.patch.object(MODULE, "ROOT", root),
        mock.patch.object(MODULE, "GUIDES", root / "guides"),
    ):
        yield


def run_main(root: Path, *args: str) -> tuple[int, str, str]:
    stdout = StringIO()
    stderr = StringIO()
    argv = ["sync_guide_labels.py", *args]
    with (
        patched_repo(root),
        mock.patch.object(MODULE.sys, "argv", argv),
        redirect_stdout(stdout),
        redirect_stderr(stderr),
    ):
        code = MODULE.main()
    return code, stdout.getvalue(), stderr.getvalue()


class SyncGuideLabelsTests(TestCase):
    maxDiff = None

    def test_group_dirs_includes_top_level_and_readme_backed_subcategories(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            build_guide_tree(root)
            (root / "guides/injection/no-readme-subdir").mkdir(parents=True)

            with patched_repo(root):
                result = MODULE.group_dirs()

            self.assertEqual(
                result,
                [
                    Path("cross-origin-communication"),
                    Path("injection"),
                    Path("injection/xss"),
                    Path("request-authenticity"),
                    Path("sensitive-data-exposure"),
                ],
            )

    def test_display_name_prefers_readme_heading_and_falls_back_to_slug(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            write(root / "guides/injection/README.md", "# Injection\n")

            with patched_repo(root):
                self.assertEqual(MODULE.display_name(Path("injection")), "Injection")
                self.assertEqual(MODULE.display_name(Path("csrf")), "CSRF")

    def test_guide_labels_uses_full_path_when_leaf_names_collide(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            write(root / "guides/browser/README.md", "# Browser\n")
            write(root / "guides/browser/shared/README.md", "# Browser Shared\n")
            write(root / "guides/server/README.md", "# Server\n")
            write(root / "guides/server/shared/README.md", "# Server Shared\n")

            with patched_repo(root):
                result = MODULE.guide_labels()

            self.assertEqual(
                result,
                [
                    ("browser", "Changes to guides in the Browser category", "guides/browser/**"),
                    ("browser-shared", "Changes to Browser Shared guides", "guides/browser/shared/**"),
                    ("server", "Changes to guides in the Server category", "guides/server/**"),
                    ("server-shared", "Changes to Server Shared guides", "guides/server/shared/**"),
                ],
            )

    def test_render_is_deterministic_and_includes_expected_headers(self) -> None:
        labels = [
            (
                "request-authenticity",
                "Changes to guides in the Request Authenticity category",
                "guides/request-authenticity/**",
            ),
            ("xss", "Changes to Cross-site scripting (XSS) guides", "guides/injection/xss/**"),
        ]

        first = MODULE.render(labels)
        second = MODULE.render(labels)

        self.assertEqual(first, second)
        self.assertIn("# DO NOT EDIT THIS FILE MANUALLY.\n", first[next(iter(first))])
        self.assertIn('- name: "request-authenticity"\n', first[MODULE.ROOT / ".github/labels.yaml"])
        self.assertTrue(first[MODULE.ROOT / ".github/labeler.yaml"].endswith("\n"))

    def test_main_writes_generated_files_and_check_then_passes(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            build_guide_tree(root)
            (root / ".github").mkdir(parents=True)

            code, stdout, stderr = run_main(root)

            self.assertEqual(code, 0)
            self.assertEqual(stderr, "")
            self.assertIn("Syncing guide label configs for 5 guide labels.", stdout)
            self.assertIn("Updated .github/labeler.yaml, .github/labels.yaml.", stdout)
            self.assertTrue((root / ".github/labeler.yaml").exists())
            self.assertTrue((root / ".github/labels.yaml").exists())

            check_code, check_stdout, check_stderr = run_main(root, "--check")

            self.assertEqual(check_code, 0)
            self.assertEqual(check_stderr, "")
            self.assertIn("Checking guide label configs for 5 guide labels.", check_stdout)
            self.assertIn("Guide label configs are up to date.", check_stdout)

    def test_main_check_reports_out_of_date_files(self) -> None:
        with TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            build_guide_tree(root)
            write(root / ".github/labeler.yaml", "stale\n")
            write(root / ".github/labels.yaml", "stale\n")

            code, stdout, stderr = run_main(root, "--check")

            self.assertEqual(code, 1)
            self.assertIn("Checking guide label configs for 5 guide labels.", stdout)
            self.assertIn(".github/labeler.yaml is out of date.", stderr)
            self.assertIn(".github/labels.yaml is out of date.", stderr)
            self.assertIn("Out-of-date files: .github/labeler.yaml, .github/labels.yaml", stderr)
