from __future__ import annotations

from hashlib import sha1
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
GUIDES = ROOT / "guides"
COMMAND = "python3 scripts/sync_guide_labels.py"
UPPERCASE_PARTS = {"xss", "csrf"}


def group_dirs() -> list[Path]:
    # Label top-level guide categories and nested subcategories that have README indexes.
    return [
        rel
        for path in sorted(p for p in GUIDES.rglob("*") if p.is_dir())
        if len((rel := path.relative_to(GUIDES)).parts) == 1 or (path / "README.md").exists()
    ]


def display_name(rel: Path) -> str:
    # Prefer the README heading so labels stay aligned with the public category names.
    readme = GUIDES / rel / "README.md"
    if readme.exists():
        for line in readme.read_text().splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return " ".join(
        part.upper() if part in UPPERCASE_PARTS else part.capitalize()
        for part in rel.name.split("-")
    )


def guide_labels() -> list[tuple[str, str, str]]:
    # Use the leaf name when it is unique; otherwise fall back to the full path.
    groups = group_dirs()
    counts: dict[str, int] = {}
    for rel in groups:
        counts[rel.name] = counts.get(rel.name, 0) + 1

    labels = []
    for rel in groups:
        name = rel.name if counts[rel.name] == 1 else "-".join(rel.parts)
        desc = (
            f"Changes to guides in the {display_name(rel)} category"
            if len(rel.parts) == 1
            else f"Changes to {display_name(rel)} guides"
        )
        labels.append((name, desc, f"guides/{rel.as_posix()}/**"))
    return labels


def color(name: str) -> str:
    # Stable, deterministic colors without maintaining a manual palette.
    return sha1(name.encode()).hexdigest()[:6]


def render(labels: list[tuple[str, str, str]]) -> dict[Path, str]:
    labeler = [
        "# This file is generated by scripts/sync_guide_labels.py.",
        f"# Run `{COMMAND}` after changing guide groups.",
        "# DO NOT EDIT THIS FILE MANUALLY.",
        "",
    ]
    for name, _, glob in labels:
        labeler += [
            f'"{name}":',
            "  - changed-files:",
            "      - any-glob-to-any-file:",
            f'          - "{glob}"',
            "",
        ]

    labels_yaml = [
        "# This file is generated by scripts/sync_guide_labels.py.",
        f"# Run `{COMMAND}` after changing guide groups.",
        "# DO NOT EDIT THIS FILE MANUALLY.",
        "",
    ]
    for name, desc, _ in sorted(labels, key=lambda row: row[0]):
        labels_yaml += [
            f'- name: "{name}"',
            f'  description: "{desc}"',
            f'  color: "{color(name)}"',
            "",
        ]

    return {
        ROOT / ".github/labeler.yaml": "\n".join(labeler).rstrip() + "\n",
        ROOT / ".github/labels.yaml": "\n".join(labels_yaml).rstrip() + "\n",
    }


def main() -> int:
    # `--check` is for CI; without it we rewrite generated files in place.
    check = "--check" in sys.argv
    labels = guide_labels()
    generated = render(labels)
    mode = "Checking" if check else "Syncing"
    print(f"{mode} guide label configs for {len(labels)} guide labels.")

    code = 0
    updated: list[str] = []
    stale: list[str] = []

    for path, content in generated.items():
        current = path.read_text() if path.exists() else ""
        if check and current != content:
            rel = str(path.relative_to(ROOT))
            stale.append(rel)
            print(f"{rel} is out of date. Run: {COMMAND}", file=sys.stderr)
            code = 1
        elif not check and current != content:
            path.write_text(content)
            updated.append(str(path.relative_to(ROOT)))

    if check and code == 0:
        print("Guide label configs are up to date.")
    elif not check and updated:
        print(f"Updated {', '.join(updated)}.")
    elif not check:
        print("Guide label configs are already up to date.")

    if stale:
        print(f"Out-of-date files: {', '.join(stale)}", file=sys.stderr)

    return code


if __name__ == "__main__":
    raise SystemExit(main())
